#!/bin/bash
zero=0
for plik in $@; do
     if ( file $plik | grep -i 'zip');
          then 
            unzip $plik
          elif ( file $plik | grep -i 'tar');
          then 
            tar -xvjf $plik
          elif ( file $plik | grep -i 'bzip2');
          then 
            tar -xvjf $plik
          elif ( file $plik | grep -i 'gzip');
          then 
             tar -xvzf $plik
          elif ( file $plik | grep -i '7-zip'); 
          then 
              7z x $plik
          else
            case $plik in
               *.tar.bz2) tar -xvjf $plik ;;
               *.bz2)     tar -xvjf $plik ;;
               *.tar.gz)  tar -xvzf $plik ;;
               *.tgz)     tar -xvzf $plik ;;
               *.gz)      gunzip $plik ;;
               *.zip)     unzip $plik ;;
               *.7z)      7z x $plik ;;
               *)         echo "Cannot unpack it !";
            esac;
     fi
done
